import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

EYE_AR_THRESHOLD = 0.22
EYE_AR_CONSEC_FRAMES = 20
YAWN_AR_THRESHOLD = 0.6
YAWN_CONSEC_FRAMES = 30
PHONE_CONFIDENCE_THRESHOLD = 0.25
PHONE_CONSEC_FRAMES = 8
GAZE_DOWN_THRESHOLD = 0.15
GAZE_AWAY_THRESHOLD = 0.18
GAZE_CONSEC_FRAMES = 30
FACE_LOST_WARNING_FRAMES = 10
FACE_LOST_CRITICAL_FRAMES = 25

KNOWN_FACES_DIR = BASE_DIR / "known_faces"
MODEL_DIR = BASE_DIR / "models"

EMERGENCY_CONTACTS = os.getenv("EMERGENCY_CONTACTS", "+1234567890")
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN", "")
TWILIO_PHONE_NUMBER = os.getenv("TWILIO_PHONE_NUMBER", "")

ALERT_SOUND_PATH = BASE_DIR / "utils" / "alert.wav"

FRAME_WIDTH = 640
FRAME_HEIGHT = 480
FPS = 30
